name: workflow 2
on: push

# second option: three jobs

jobs:
  
  execute lint:
    runs-on: ubuntu-latest

    steps:
      -name: Code download
       uses: actions/checkout@v3

      -name: install dependences
       run: npm ci

      -name: execute lint
       run: npm lint

  execute test:
    runs-on: ubuntu-latest
    steps:
      -name: Code download
      uses: actions/checkout@v3

      -name: install dependences
      run: npm ci

      -name: execute tests
      run: npm test

  execute build and deploy:
    runs-on: ubuntu-latest
    steps:
      -name: Code download
       uses: actions/checkout@v3

      -name: install dependences
       run: npm ci

      -name: build project
       run: npm build

      -name: deploy project
       echo: "deploy in the server"
      
