name: workflow 1
on: push

# first option: only a job
# Try to connect with user 
jobs:
  # the name
  info:
    runs-on: ubuntu-latest

    steps:
      - name: Get Code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci
      # npm ci pega exatamente as mesmas versões que usamos durante o desenvolvimento.

      - name: Execute lint
        run: npm run lint
      # npm run para executar os scripts do package.json.

      - name: Execute tests
        run: npm run test

      - name: Build project
        run: npm run build

      - name: Deploy project
        run: echo "deploy in the server"
