name: workflow 2
on: push

# second option: three jobs

jobs:
  
  execute lint:
    runs-on: ubuntu-latest

    steps:
    -name: Code download
     uses: action/checkout@v3

    -name: install dependences
     run: npm ci

    -name: execute lint
     run: npm lint

  execute test:
    -name: Code download
     uses: action/checkout@v3

    -name: install dependences
     run: npm ci

    -name: execute tests
     run: npm test

  execute build and deploy:
    -name: Code download
     uses: action/checkout@v3

    -name: install dependences
     run: npm ci

    -name: build project
     run: npm build

    -name: deploy project
     echo: "deploy in the server"
    
