name: workflow 2
on: push

jobs:
  execute-lint:  # Não pode ter espaços no nome
    runs-on: ubuntu-latest
    steps:
      - name: Code download
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Execute lint
        run: npm run lint

  execute-test:
    runs-on: ubuntu-latest
    steps:
      - name: Code download
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Execute tests
        run: npm test

  execute-build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Code download
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy project
        run: echo "Deploying to the server"
