name: workflow 1
on: push

# first option: only a job
# Try to connect with user 
jobs:
  # the name
  info:
    runs-on: ubuntu-latest

    steps:
      -name: Get Code
       uses: action/checkout@v3

      -name: install dependences
       run: npm ci
      #  run allow execute command in shell
      # npm ci pega exatamente as mesmas versões que usamos durante o desenvolvimento, diferente do npm install, que pega as mais recentes.

      -name: execute lint
       run: npm run lint
      #  npm run para executar os scripts do package.json

      -name: execute tests
       run: npm run test

      -name: build project
       run: npm run build

      -name: deploy project
       run: echo "deploy in the server"
      
